services:
  web:
    build: .
    image: mywebapp
    ports:
      - "127.0.0.1:15000:5000"
    depends_on:
      - db
    networks:
      - frontend
    read_only: true
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    pids_limit: 100

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydb
    networks:
      - backend
networks:
  frontend:
  backend:
